# Generated by Django 4.2.15 on 2024-09-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_remove_expertindexpage_outro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertindexpage",
            name="outro_button_text",
            field=models.CharField(
                blank=True,
                default="Who we are",
                help_text="Example: Who we are",
                max_length=255,
                verbose_name="Button text",
            ),
        ),
        migrations.AddField(
            model_name="expertindexpage",
            name="outro_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Page",
            ),
        ),
        migrations.AddField(
            model_name="expertindexpage",
            name="outro_title",
            field=models.CharField(
                blank=True,
                default="Who are the people behind ...?",
                help_text="Example: Who are the people behind ...?",
                max_length=255,
                verbose_name="Title",
            ),
        ),
    ]
