# Generated by Django 4.2.16 on 2025-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_expertindexpage_outro_button_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="youtube_video_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This ID of the video on Youtube,the part after 'embed/'",
                max_length=20,
                null=True,
                verbose_name="Youtube Video ID",
            ),
        ),
    ]
