# Generated by Django 4.2.16 on 2025-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_carboncalculatorpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonEmissionCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this CarbonEmission category",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "conversion_to_kg_CO2",
                    models.FloatField(
                        default=1, help_text="The conversion ratio to 1kg of CO2"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A description for this category",
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="A URL for an image depicting this category",
                        null=True,
                    ),
                ),
                (
                    "source_description",
                    models.CharField(
                        blank=True,
                        help_text="A description of the source of this conversion number",
                        max_length=255,
                        null=True,
                        verbose_name="source_description",
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True,
                        help_text="A URL for  the source of this conversion number",
                        max_length=255,
                        null=True,
                        verbose_name="source_url",
                    ),
                ),
                (
                    "is_emission",
                    models.BooleanField(
                        default=True,
                        help_text="True if it is a CO2 emission, False if it is a CO2 absorbtion",
                        verbose_name="is_emission",
                    ),
                ),
            ],
            options={
                "verbose_name": "CO2 emission category",
                "verbose_name_plural": "CO2 emission categories",
                "ordering": ["name"],
            },
        ),
    ]
