# Generated by Django 3.2.16 on 2022-11-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsInProgressPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Questions in progress page',
                'verbose_name_plural': 'Questions in progress pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
