# Generated by Django 3.2.16 on 2022-11-28 14:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_questionsinprogresspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(default='<p>Wij willen je vraag graag zo compleet en correct mogelijk beantwoorden. Daarom vragen wij twee experts die voor jou aan de slag gaan om een antwoord te formuleren. De één doorzoekt bronnen en discussiëert, de ander gaat alles nog eens grondig controleren. Het kost wel wat tijd om deze wetenschappelijke standaard voor een betrouwbaar antwoord te behalen. Daarom kan het wat langer duren voordat je vraag beantwoord is.</p>', verbose_name='Intro')),
                ('step_1_title', models.CharField(default='Waar gaat je vraag over?', max_length=255, verbose_name='Titel')),
                ('step_2_title', models.CharField(default='Formuleer je vraag', max_length=255, verbose_name='Titel')),
                ('keep_me_posted_title', models.CharField(default='Bedankt voor je vraag!', max_length=255, verbose_name='Titel')),
                ('keep_me_posted_text', wagtail.fields.RichTextField(default='<p>Laat je mailadres achter als je op de hoogte gehouden wilt worden. Dit is optioneel.</p>', verbose_name='Tekst')),
                ('thank_you_text', wagtail.fields.RichTextField(default='<p>Bedankt voor het stellen van je vraag. We nemen je vraag in behandeling en proberen zo snel mogelijk een expert te vinden die je vraag kan beantwoorden.</p>', verbose_name='Tekst')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
