# Generated by Django 3.2.16 on 2022-11-30 12:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_expertansweroverviewpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNavSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default="Didn't find the answer you were looking for?", max_length=255, verbose_name='Text')),
                ('buttons', wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(verbose_name='Title')), ('page', wagtail.blocks.PageChooserBlock(verbose_name='Page'))]))], blank=True, use_json_field=None, verbose_name='Buttons')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Main navigation',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_text', wagtail.fields.RichTextField(default='<p>An initiative of <a href="#">...</a> & <a href="#">...</a></p>', verbose_name='Initiator-text')),
                ('nav', wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(verbose_name='Title')), ('page', wagtail.blocks.PageChooserBlock(verbose_name='Page'))]))], blank=True, use_json_field=None, verbose_name='Navigation')),
                ('maintainer_text', models.TextField(default='example.com is managed by ..., a non-profit organization, registered under Chamber of Commerce number ...', max_length=255, verbose_name='Maintainer text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
    ]
