# Generated by Django 3.2.16 on 2022-12-13 14:57

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20221213_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickysettings',
            options={'verbose_name': 'Sticky menu'},
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_buttons',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(verbose_name='Titel')), ('page', wagtail.blocks.PageChooserBlock(verbose_name='Pagina'))]))], blank=True, use_json_field=None, verbose_name='Buttons'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='expert_buttons',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(verbose_name='Titel')), ('page', wagtail.blocks.PageChooserBlock(verbose_name='Pagina'))]))], blank=True, use_json_field=None, verbose_name='Buttons'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='expert_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='expert_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='nav',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(verbose_name='Titel')), ('page', wagtail.blocks.PageChooserBlock(verbose_name='Pagina'))]))], blank=True, use_json_field=None, verbose_name='Navigation'),
        ),
    ]
