# Generated by Django 3.2.18 on 2023-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='How the question is displayed on the (questions pending) page, only approved questions are shown', verbose_name='Your Question')),
                ('original_question', models.TextField(blank=True, verbose_name='Original Question')),
                ('relevant_timespan', models.TextField(blank=True, verbose_name='Relevant timespan')),
                ('relevant_location', models.TextField(blank=True, verbose_name='Relevant location')),
                ('extra_info', models.TextField(blank=True, verbose_name='Extra information')),
                ('categories', models.TextField(blank=True, verbose_name='Categories')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='User Email')),
                ('asked_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Undecided'), (1, 'Approved'), (2, 'Answered'), (3, 'Rejected')], default=0)),
            ],
        ),
    ]
