# Generated by Django 3.2.16 on 2022-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_question_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.TextField(blank=True, default='', verbose_name='Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='extra_info',
            field=models.TextField(blank=True, default='', verbose_name='Extra information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='original_question',
            field=models.TextField(blank=True, default='', verbose_name='Original Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='How the question is displayed on the (questions pending) page, only approved questions are shown', verbose_name='Your Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='relevant_location',
            field=models.TextField(blank=True, default='', verbose_name='Relevant location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='relevant_timespan',
            field=models.TextField(blank=True, default='', verbose_name='Relevant timespan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='User Email'),
            preserve_default=False,
        ),
    ]
