# Generated by Django 3.2.16 on 2022-12-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221128_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitlabIssues',
        ),
    ]
